apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: query-api
  namespace: supply-shock
spec:
  ingressClassName: nginx
  rules:
    - host: supplyshock.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: query-api
                port:
                  number: 80
