apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: supply-shock
resources:
  - namespace.yaml
  - configmap.yaml
  - query-api-deployment.yaml
  - query-api-service.yaml
  - ingress.yaml
