apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: supply-shock
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - query-api-deployment.yaml
  - query-api-service.yaml
  - query-api-hpa.yaml
  - ingest-deployment.yaml
  - ingest-service.yaml
  - risk-engine-deployment.yaml
  - risk-engine-hpa.yaml
  - alert-service-deployment.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - ingress.yaml
