apiVersion: v1
kind: Secret
metadata:
  name: supply-shock-secrets
  namespace: supply-shock
type: Opaque
stringData:
  database-url: "postgres://postgres:postgres@postgres.default.svc.cluster.local:5432/supplyshock?sslmode=disable"
  kafka-brokers: "kafka-bootstrap.kafka.svc.cluster.local:9092"
